version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:3001"  # Adjust the port as needed
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"  # Adjust the port as needed
